apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "capstone-chart-vulnerable-php83.fullname" . }}-nginx
  labels:
    app: {{ include "capstone-chart-vulnerable-php83.name" . }}
    chart: {{ include "capstone-chart-vulnerable-php83.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ include "capstone-chart-vulnerable-php83.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "capstone-chart-vulnerable-php83.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "capstone-chart-vulnerable-php83.fullname" . }}-php
  labels:
    app: {{ include "capstone-chart-vulnerable-php83.name" . }}
    chart: {{ include "capstone-chart-vulnerable-php83.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.php.replicas }}
  selector:
    matchLabels:
      app: {{ include "capstone-chart-vulnerable-php83.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "capstone-chart-vulnerable-php83.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: php
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
          ports:
            - containerPort: 9000
          resources:
            {{- toYaml .Values.php.resources | nindent 12 }}
