{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "capstone-chart-vulnerable-php83.fullname" . }}-route
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host:
      http:
        paths:
          - path: /php
            pathType: Exact
            backend:
              service:
                name: {{ include "capstone-chart-vulnerable-php83.fullname" . }}-nginx
                port:
                  number: 80
{{- end }}