apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "capstone-chart-vulnerable-php83.fullname" . }}-route
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /php
            pathType: Exact
            backend:
              service:
                name: {{ include "capstone-chart-vulnerable-php83.fullname" . }}-nginx
                port:
                  number: 80
    {{- end }}
