apiVersion: v1
kind: Service
metadata:
  name: {{ include "capstone-chart-vulnerable-php83.fullname" . }}-nginx
  labels:
    app: {{ include "capstone-chart-vulnerable-php83.name" . }}
    chart: {{ include "capstone-chart-vulnerable-php83.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ include "capstone-chart-vulnerable-php83.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    app: {{ include "capstone-chart-vulnerable-php83.name" . }}
    chart: {{ include "capstone-chart-vulnerable-php83.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.php.service.type }}
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: {{ include "capstone-chart-vulnerable-php83.name" . }}
    release: {{ .Release.Name }}
